CC=gcc -Wall -std=c11

rect:
	$(CC) lodepng_test.c lodepng.c -o rectify

pool:
	$(CC) lodepng_test.c lodepng.c -o pooling

conv:
	$(CC) lodepng_test.c lodepng.c -o convolution

clean:
	-rm -f rectify
	-rm -f convolution
	-rm -f pooling
